# -*- coding: utf-8 -*-
"""
Django settings for OSVRCMS20170623 project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'jys*ap)h5xf@1f%qqkn9#)0&fz@71vv8nyhrmpv6uba1_nj14l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1','localhost','osvr-dev.lianluo.com','139.198.9.154','julianyang.free.ngrok.cc']



# Application definition

INSTALLED_APPS = [
    'suit',
   # 'grappelli.dashboard',
   # 'grappelli',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'captcha',

    'django.contrib.sites',
    'django.contrib.flatpages',
    'crispy_forms',

    'chartit',
    'chartjs',

    'statistics',
    'CMS',
    'rest_framework',
    'rest_framework.authtoken',
    'easy_thumbnails',
    'filer',
    'mptt',

    #...
    # 'dash',
    # 'dash.contrib.layouts.android',
    # 'dash.contrib.layouts.bootstrap2',
    # 'dash.contrib.layouts.windows8',
    # 'dash.contrib.plugins.dummy',
    # 'dash.contrib.plugins.image',
    # 'dash.contrib.plugins.memo',
    # 'dash.contrib.plugins.rss_feed',
    # 'dash.contrib.plugins.url',
    # 'dash.contrib.plugins.video',
    # 'dash.contrib.plugins.weather',
    # ...
]




REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    #'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAuthenticated',),
    'DEFAULT_AUTHENTICATION_CLASSES': ('rest_framework.authentication.TokenAuthentication',),
    'PAGE_SIZE': 10,
    'PAGINATE_BY': 10
}
THUMBNAIL_HIGH_RESOLUTION  =  True

THUMBNAIL_PROCESSORS  =  (
    'easy_thumbnails.processors.colorspace' ,
    'easy_thumbnails.processors.autocrop',
    'easy_thumbnails.processors.scale_and_crop',
    'filer.thumbnail_processors.scale_and_crop_with_subject_location' ,
    'easy_thumbnails.processors.filters' ,
)


MIDDLEWARE = [
    # 'django.middleware.cache.UpdateCacheMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware'
    # 'django.middleware.cache.FetchFromCacheMiddleware',
]

ROOT_URLCONF = 'OSVRCMS20170623.urls'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache', #文件方式
        'LOCATION': os.path.join(BASE_DIR, 'cache'),
        'TIMEOUT': 600,
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    }
}



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'neu'),
            os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries': {
                'get_file': 'CMS.templatetags.get_file',
                'get_file_image_aliases':'CMS.templatetags.get_file_image_aliases'

            }



        },
    },
]

WSGI_APPLICATION = 'OSVRCMS20170623.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }
DATABASES = {
    'default':{
        'ENGINE'  :'django.db.backends.mysql',
        'NAME'    :'osvr_cms20170620',
        'USER'    :'root',
        'PASSWORD':'111111',
        'HOST'    :'localhost',#ip
        'PORT'    :'3306',
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



LANGUAGE_CODE = 'zh-Hans'  # 设置成中文，老版本django使用'zh_CN'
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True
USE_L10N = True            # 注意是False 配合下边时间格式
USE_TZ = False             # 如果只是内部使用的系统，这行建议为false，不然会有时区问题
DATETIME_FORMAT = 'Y-m-d'  # suit在admin里设置时间的一个小bug。需要把时间格式指定一下
DATE_FORMAT = 'Y-m-d'

SUIT_CONFIG = {  # suit页面配置
    'ADMIN_NAME': 'VR助手管理后台',  #登录界面LOGO
    'SHOW_REQUIRED_ASTERISK':True,
    'HEADER_TIME_FORMAT': 'H:i',
    'LIST_PER_PAGE': 10,
    'MENU':(
        {'label': u"用户管理", "icon": 'icon-user', "models": [
            {"label": u"注册用户信息", 'url': '/BhfVCvJzeSQm/CMS/user/'},
            #{"label": u"开发者申请信息", 'url': '/admin/CMS/userprofile/'},
        ]},
        {'label': u'游戏管理',"icon": 'icon-briefcase', "models": [
            {"label": u'游戏类型', 'url': '/BhfVCvJzeSQm/CMS/genres/'},
            {"label": u'游戏平台', 'url': '/BhfVCvJzeSQm/CMS/device/'},
            {"label": u'游戏配件', 'url': '/BhfVCvJzeSQm/CMS/fittings/'},
            {"label": u'游戏内容', 'url': '/BhfVCvJzeSQm/CMS/game/'}
        ]},
        {'label': u'视频管理',"icon": 'icon-facetime-video', "models": [
            {"label": u'视频类型', 'url': '/BhfVCvJzeSQm/CMS/videogenres/'},
            {"label": u'视频分类', 'url': '/BhfVCvJzeSQm/CMS/videosort/'},
            {"label": u'视频内容', 'url': '/BhfVCvJzeSQm/CMS/video/'},
        ]},
        {'label': u'图片管理', "icon": 'icon-picture', "models": [
            {"label": u'图片类型', 'url': '/BhfVCvJzeSQm/CMS/imagegenres/'},
            {"label": u'图片分类', 'url': '/BhfVCvJzeSQm/CMS/imagesort/'},
            {"label": u'图片内容', 'url': '/BhfVCvJzeSQm/CMS/image/'},
        ]},

        {'label': u'应用管理',"icon": 'icon-file', "models": [
            {"label": u'应用类型', 'url': '/BhfVCvJzeSQm/CMS/appgenres/'},
            {"label": u'应用内容', 'url': '/BhfVCvJzeSQm/CMS/app/'},
        ]},
        {'label':u'评论管理','icon':'icon-comment',"models":[
             {'label':u'游戏评论','url':'/BhfVCvJzeSQm/CMS/topic'},
             {'label':u'视频评论','url':'/BhfVCvJzeSQm/CMS/videotopic'},
             {'label':u'应用评论','url':'/BhfVCvJzeSQm/CMS/apptopic'},
        ]},
        {'label':u'广告资源','icon':'icon-gift',"models":[
             {'label':u'广告资源','url':'/BhfVCvJzeSQm/CMS/ad'},
        ]},
        {'label':u'VR助手版本管理','icon':'icon-file','models':[
            {'label': u'软件升级包管理', 'url': '/BhfVCvJzeSQm/CMS/appupdatemessage'},
            {'label': u'固件升级包管理', 'url': '/BhfVCvJzeSQm/CMS/firmwareupdatemessage'},
            {'label': u'固件厂商管理', 'url': '/BhfVCvJzeSQm/CMS/manufactor'},
            {'label': u'固件类型管理', 'url': '/BhfVCvJzeSQm/CMS/fwaretype'},
        ]},
        {'label': u'VR助手统计管理', 'icon': 'icon-picture', "models": [
            {'label': u'VR助手数据统计', 'url': '/BhfVCvJzeSQm/statistics/appheart/installedbase'},
            {'label': u'VR助手心跳检测', 'url': '/BhfVCvJzeSQm/statistics/appheart/'},
        ]},

        {'label':u'文件管理器','icon':'icon-picture',"models":[
             {'label':u'文件浏览器','url':'/BhfVCvJzeSQm/filer/folder'},
             {'label': u'缩略图选项', 'url': '/BhfVCvJzeSQm/filer/thumbnailoption'},
             {'label': u'文件夹权限', 'url': '/BhfVCvJzeSQm/filer/folderpermission'},
        ]},
        {'label': u'Client申请', 'icon': 'icon-comment', "models": [
            {'label': u'PC', 'url': '#'},
            {'label': u'ANDROID', 'url': '#'},
            {'label': u'IOS', 'url': '#'},
        ]},
        {'app': 'auth', 'label': u'认证和授权', 'icon': 'icon-lock'},
    )
}
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/
#STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_ROOT = os.path.join(BASE_DIR, 'static').replace('\\','/')
STATIC_URL = '/static/'



MEDIA_ROOT = os.path.join(BASE_DIR,'media')
MEDIA_URL = '/media/'

FILER_CANONICAL_URL  =  'sharing/'
STATICFILES_DIRS = (
  ("static", STATIC_ROOT+"static"),
  ("media", MEDIA_ROOT+"media"),
)
URL = "http://127.0.0.1:8000"



THUMBNAIL_ALIASES = {
    '': {
        'videocover': {'size':(259, 146), 'crop':True},
        'videorecommendcover':{'size':(75,75), 'crop':True},
        'videorecommendban':{'size':(1100,425), 'crop':True},
        'gamecover':  {'size':(259, 146), 'crop':True},
        'imagecover': {'size':(359, 190), 'crop':True},
        'imageban':{'size':(1084,400),'crop':True},
    },
}


# django_simple_captcha 验证码配置
# 格式
CAPTCHA_OUTPUT_FORMAT = u'%(text_field)s %(hidden_field)s %(image)s'
# 噪点样式
CAPTCHA_NOISE_FUNCTIONS = (#'captcha.helpers.noise_null',  # 没有样式
                            'captcha.helpers.noise_arcs', # 线
                            #'captcha.helpers.noise_dots', # 点
                           )
# 图片大小
CAPTCHA_IMAGE_SIZE = (100, 30)
CAPTCHA_BACKGROUND_COLOR = '#ffffff'
#CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.random_char_challenge'  # 图片中的文字为随机英文字母，如 mdsh
CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.math_challenge'    # 图片中的文字为数字表达式，如1+2=</span>

CAPTCHA_LENGTH = 4  # 字符个数
CAPTCHA_TIMEOUT = 1  # 超时(minutes)

#TOKEN的有效时间
PASSWORD_RESET_TIMEOUT_DAYS = 1