# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-03 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        ('CMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufactor',
            name='LOGO_PATH',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.File', verbose_name='\u8d44\u6e90\u6587\u4ef6'),
        ),
    ]
