# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-24 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0002_manufactor_logo_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u5206\u7c7b\u540d\u79f0')),
                ('shortname', models.CharField(default=None, max_length=10, verbose_name='\u7b80\u79f0')),
                ('enname', models.CharField(default=None, max_length=30, verbose_name='\u82f1\u6587\u540d')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'ordering': ('created_at',),
                'verbose_name': '\u89c6\u9891\u5206\u7c7b',
                'verbose_name_plural': '\u89c6\u9891\u5206\u7c7b',
            },
        ),
        migrations.AlterField(
            model_name='manufactor',
            name='LOGO_PATH',
            field=models.OneToOneField(help_text='\u6587\u4ef6\u7ba1\u7406\u5668', null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.File', verbose_name='LOGO ID'),
        ),
        migrations.AlterField(
            model_name='video',
            name='Genres',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CMS.VideoGenres', verbose_name='\u89c6\u9891\u7c7b\u578b'),
        ),
    ]
