# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-24 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0003_auto_20171024_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='Sort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CMS.VideoSort', verbose_name='\u89c6\u9891\u5206\u7c7b'),
        ),
    ]
