# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-24 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0004_video_sort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='Sort',
        ),
        migrations.AddField(
            model_name='video',
            name='Sort',
            field=models.ManyToManyField(to='CMS.VideoSort', verbose_name='\u89c6\u9891\u5206\u7c7b'),
        ),
    ]
