  # -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-24 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0005_auto_20171024_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='playcount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='\u64ad\u653e\u6570'),
        ),
        migrations.AlterField(
            model_name='video',
            name='videocover',
            field=models.ImageField(help_text='sss', upload_to='./video/cover/%Y/%m/%d', verbose_name='\u5c01\u9762'),
        ),
    ]
