# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-24 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0008_auto_20171024_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='score',
            field=models.FloatField(default=0, null=True, verbose_name='\u8bc4\u5206'),
        ),
    ]
