# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-24 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0009_auto_20171024_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='filecapacity',
            field=models.FloatField(null=True, verbose_name='\u5bb9\u91cf\u5927\u5c0f'),
        ),
    ]
