# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-24 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0010_auto_20171024_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='playcount',
            field=models.IntegerField(null=True, verbose_name='\u64ad\u653e\u6570'),
        ),
    ]
