# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-24 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0012_auto_20171024_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGenres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u7c7b\u578b\u540d\u79f0')),
                ('shortname', models.CharField(default=None, max_length=10, verbose_name='\u7b80\u79f0')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'ordering': ('created_at',),
                'verbose_name': '\u56fe\u7247\u7c7b\u578b',
                'verbose_name_plural': '\u56fe\u7247\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='ImageSort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u5206\u7c7b\u540d\u79f0')),
                ('shortname', models.CharField(default=None, max_length=10, verbose_name='\u7b80\u79f0')),
                ('enname', models.CharField(default=None, max_length=30, verbose_name='\u82f1\u6587\u540d')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'ordering': ('created_at',),
                'verbose_name': '\u56fe\u7247\u5206\u7c7b',
                'verbose_name_plural': '\u56fe\u7247\u5206\u7c7b',
            },
        ),
    ]
