# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-24 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        ('CMS', '0013_imagegenres_imagesort'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u56fe\u7247\u540d\u79f0')),
                ('synopsis', models.TextField(blank=True, null=True, verbose_name='\u6982\u8981')),
                ('score', models.FloatField(default=0, null=True, verbose_name='\u8bc4\u5206')),
                ('playcount', models.IntegerField(null=True, verbose_name='\u64ad\u653e\u6570')),
                ('is_recommend', models.BooleanField(default=False, verbose_name='\u63a8\u8350')),
                ('is_latest', models.BooleanField(default=False, verbose_name='\u6700\u65b0')),
                ('is_hottest', models.BooleanField(default=False, verbose_name='\u6700\u70ed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('Genres', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CMS.ImageGenres', verbose_name='\u56fe\u7247\u7c7b\u578b')),
                ('Sort', models.ManyToManyField(to='CMS.ImageSort', verbose_name='\u56fe\u7247\u5206\u7c7b')),
                ('imageurl', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.File', verbose_name='\u56fe\u7247\u7f51\u5740\u6587\u4ef6')),
            ],
            options={
                'ordering': ('created_at',),
                'verbose_name': '\u56fe\u7247\u5185\u5bb9',
                'verbose_name_plural': '\u56fe\u7247\u5185\u5bb9',
            },
        ),
    ]
