# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-24 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0014_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='synopsis',
            field=models.TextField(blank=True, default=0, null=True, verbose_name='\u6982\u8981'),
        ),
    ]
