# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-24 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0015_auto_20171024_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='score',
            field=models.FloatField(null=True, verbose_name='\u8bc4\u5206'),
        ),
        migrations.AlterField(
            model_name='image',
            name='synopsis',
            field=models.TextField(blank=True, null=True, verbose_name='\u6982\u8981'),
        ),
    ]
