# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-25 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0017_auto_20171024_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='Device',
        ),
        migrations.AddField(
            model_name='game',
            name='Device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CMS.Device', verbose_name='\u652f\u6301\u5e73\u53f0'),
        ),
    ]
