# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-25 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0018_auto_20171025_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fittings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u914d\u4ef6\u540d\u79f0')),
                ('enname', models.CharField(max_length=50, verbose_name='\u82f1\u6587\u540d\u79f0')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'ordering': ('created_at',),
                'verbose_name': '\u6e38\u620f\u914d\u4ef6',
                'verbose_name_plural': '\u6e38\u620f\u914d\u4ef6',
            },
        ),
    ]
