# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-25 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0019_fittings'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='Fittings',
            field=models.ManyToManyField(to='CMS.Fittings', verbose_name='\u6e38\u620f\u914d\u4ef6'),
        ),
    ]
