# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-25 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0020_game_fittings'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='playcount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='\u6253\u5f00\u6570'),
        ),
    ]
