# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-25 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0026_auto_20171025_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='filepath',
            field=models.FileField(upload_to='./game/file/%Y/%m/%d', verbose_name='\u8d44\u6e90\u5305'),
        ),
    ]
