# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-25 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0029_auto_20171025_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videopath',
            field=models.FileField(blank=True, upload_to='./video/file/%Y/%m/%d', verbose_name='\u89c6\u9891\u6587\u4ef6'),
        ),
    ]
