# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-25 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0033_auto_20171025_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='apppath',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.File', verbose_name='\u5e94\u7528\u6587\u4ef6'),
        ),
        migrations.AlterField(
            model_name='video',
            name='playcount',
            field=models.IntegerField(default=0, null=True, verbose_name='\u64ad\u653e\u6570'),
        ),
    ]
