# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-26 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0035_auto_20171026_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='filepath',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.File', verbose_name='\u6e38\u620f\u8d44\u6e90\u5305'),
        ),
        migrations.RemoveField(
            model_name='image',
            name='Sort',
        ),
        migrations.AddField(
            model_name='image',
            name='Sort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CMS.ImageSort', verbose_name='\u56fe\u7247\u5206\u7c7b'),
        ),
    ]
