# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-20 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0036_auto_20171026_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesort',
            name='folder_id',
            field=models.IntegerField(default=0, verbose_name='\u6587\u4ef6\u5939ID'),
        ),
        migrations.AlterField(
            model_name='imagesort',
            name='enname',
            field=models.CharField(default=None, max_length=30, unique=True, verbose_name='\u82f1\u6587\u540d'),
        ),
        migrations.AlterField(
            model_name='imagesort',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='\u5206\u7c7b\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='imagesort',
            name='shortname',
            field=models.CharField(default=None, max_length=10, unique=True, verbose_name='\u7b80\u79f0'),
        ),
    ]
