# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-20 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0038_remove_imagesort_folder_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imageurl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.File', unique=True, verbose_name='\u56fe\u7247\u7f51\u5740\u6587\u4ef6'),
        ),
    ]
