# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-20 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0039_auto_20171120_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesort',
            name='folder_id',
            field=models.CharField(default=0, max_length=100, verbose_name='\u6587\u4ef6\u5939ID'),
        ),
    ]
