# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-24 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0040_imagesort_folder_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, verbose_name='Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('user_id', models.IntegerField(verbose_name='\u7528\u6237ID')),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='imageurl',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.File', verbose_name='\u56fe\u7247\u7f51\u5740\u6587\u4ef6'),
        ),
    ]
