# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-24 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0042_auto_20171124_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='expire_date',
            field=models.DateTimeField(null=True, verbose_name='\u5931\u6548\u65f6\u95f4'),
        ),
    ]
