# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-27 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0043_usertoken_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='local',
            field=models.IntegerField(choices=[(1, '\u7cbe\u9009'), (2, '\u5f71\u89c6'), (3, '\u56fe\u7247'), (4, '\u6e38\u620f'), (5, '\u76f4\u64ad'), (6, '\u5176\u5b83')], verbose_name='\u8d44\u6e90\u4f4d\u7f6e'),
        ),
    ]
