# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-27 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0044_auto_20171127_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u8bc4\u5206'),
        ),
        migrations.AddField(
            model_name='ad',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u6807\u9898'),
        ),
    ]
