# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-27 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0045_auto_20171127_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='starring',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u4e3b\u6f14'),
        ),
    ]
