# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-27 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0046_video_starring'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
