# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-27 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0048_auto_20171127_1639'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoodsImage',
        ),
    ]
