# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-27 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0049_delete_goodsimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gamecover',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='./game/cover/%Y/%m/%d', verbose_name='\u5c01\u9762'),
        ),
        migrations.AlterField(
            model_name='game',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='./game/img/%Y/%m/%d', verbose_name='\u4e3b\u56fe'),
        ),
    ]
