# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-27 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0050_auto_20171127_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='sorting',
            field=models.IntegerField(default=255, verbose_name='\u6392\u5e8f'),
        ),
    ]
