# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-30 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0051_image_sorting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='sorting',
            field=models.IntegerField(blank=True, default=255, verbose_name='\u6392\u5e8f'),
        ),
    ]
