# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-30 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0052_auto_20171130_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(blank=True, default='zzz', max_length=255, null=True, verbose_name='\u6807\u9898'),
        ),
    ]
