# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-30 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0054_auto_20171130_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=249, verbose_name='\u56fe\u7247\u540d\u79f0'),
        ),
    ]
