# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-30 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0055_auto_20171130_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='t',
            field=models.CharField(default=None, max_length=30, verbose_name='\u7c7b\u578b\u540d\u79f0t'),
        ),
        migrations.AddField(
            model_name='imagegenres',
            name='t',
            field=models.CharField(default=None, max_length=30, verbose_name='\u7c7b\u578b\u540d\u79f0t'),
        ),
        migrations.AddField(
            model_name='imagesort',
            name='t',
            field=models.CharField(default=None, max_length=30, verbose_name='\u7c7b\u578b\u540d\u79f0t'),
        ),
    ]
