# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-30 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0056_auto_20171130_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='t',
        ),
        migrations.RemoveField(
            model_name='imagegenres',
            name='t',
        ),
        migrations.RemoveField(
            model_name='imagesort',
            name='t',
        ),
    ]
