# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-30 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0059_auto_20171130_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='starring',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='\u4e3b\u6f14'),
        ),
    ]
