# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-26 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppHeart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('APPIP', models.CharField(max_length=50, null=True, verbose_name='IP')),
                ('MACADDRESS', models.CharField(max_length=50, verbose_name='MAC\u5730\u5740')),
                ('LOGINTIME', models.CharField(max_length=500, null=True, verbose_name='\u521d\u6b21\u5fc3\u8df3\u65f6\u95f4')),
                ('HEARTRATE', models.IntegerField(default=0, null=True, verbose_name='\u5fc3\u8df3\u9891\u7387')),
                ('ONLINETIME', models.CharField(max_length=50, null=True, verbose_name='\u5728\u7ebf\u65f6\u957f(s)')),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('UPDATAD_AT', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'ordering': ('CREATED_AT',),
                'verbose_name': '\u5fc3\u8df3\u68c0\u6d4b',
                'verbose_name_plural': '\u5fc3\u8df3\u68c0\u6d4b',
            },
        ),
    ]
