# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-27 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0003_auto_20170626_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appheart',
            options={'ordering': ('CREATED_AT',), 'verbose_name': '\u5ba2\u6237\u7aef\u5fc3\u8df3\u68c0\u6d4b', 'verbose_name_plural': '\u5ba2\u6237\u7aef\u5fc3\u8df3\u68c0\u6d4b'},
        ),
    ]
